# Generated by Django 2.2.10 on 2020-03-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_panaderia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('articulo', models.CharField(max_length=50)),
            ],
        ),
    ]
